# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ktpersonal
# "service" is the name of this project. This will also be added to your AWS resource names.
service: exam-aws-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment: 
    JWT_SECRET: ${ssm:/for-class/aws/ticket-app/jwt-secret}
    USER_TABLE: examUser-db
  role: ${ssm:/for-class/iam/role}

package:
  individually: true

build:
  esbuild: 
    minify: true

resources:
  Resources:
    ticketAppUsersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: examUser-db
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


functions:
  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: '/auth/signUp'
          method: POST

  signIn:
    handler: functions/signIn/index.handler
    events:
      - httpApi:
          path: '/auth/signIn'
          method: POST